# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Leesin's Blog
subtitle: To be a better me
description: To be a better me
keywords: 
author: Leesin.Dong
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: http://yoursite.com
url: http://mmmmmm.me
 #
#   http://dataiyangu.github.io
#  gitee:https://dataiyangu.gitee.iohe
root: /
#permalink: :year/:month/:day/:title/
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
#  https://gitee.com/dataiyangu/dataiyangu.git
#   github: git@github.com:dataiyangu/dataiyangu.github.io.git
#   github: https://github.com/dataiyangu/dataiyangu.github.io.git
#   coding: git@git.dev.tencent.com:dataiyangu/dataiyangu.git
#   coding: https://git.dev.tencent.com/dataiyangu/dataiyangu.git
   oschina: https://gitee.com/ilxx/ilxx.git
  branch: master




feed: # RSS订阅插件
  type: atom
  path: atom.xml
  limit: 0

plugins: hexo-generate-feed


#添加搜索
algolia:
  applicationID: 'P88H67GUII'
  apiKey: '5489ac7ce78f59f4a8cb5445035f54d8'
  indexName: 'dataiyangu'
  chunkSize: 5000





live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  model:
    use: histoire
  display:
    superSample: 2
    width: 125
    height: 125
    position: left
    hOffset: 30
    vOffset: -20
  mobile:
    show: false
    scale: 0.05
  react:
    opacityDefault: 1
    opacityOnHover: 0.2


admin:
   secret: hey hexo
   deployCommand: './admin_script/hexo-generate.sh'
  # expire: 60*1

#  设置百度和谷歌map

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#自定义版权
copyright_my: true

# hexo-neat
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'
#    - '**/love.js'
    - '**/comments.gitalk.js'
    - '**/jquery_pjax_min_js.js'
    - '**/aplayer.js'


